name: Full Stack CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'ecohero-frontend/**'
      - 'ecohero-backend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'ecohero-frontend/**'
      - 'ecohero-backend/**'

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js for Backend
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - run: cd ecohero-backend && npm install
    - run: cd ecohero-backend && npm test
    - name: Build Backend
      run: cd ecohero-backend && npm run build

  frontend:
    needs: backend
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js for Frontend
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - run: cd ecohero-frontend && npm install
    - run: cd ecohero-frontend && npm test
    - name: Build Frontend
      run: cd ecohero-frontend && npm run build
